name: iml
dependencies:
  - python>=3.8.1
  - numpy
  - pandas
  - scikit-learn
  - tqdm          # https://tqdm.github.io
  - ipykernel
  - matplotlib 
  - pytorch
  - pytorch::torchvision
  - pip
  - pip:
    - opencv-python