name: iml
dependencies:
  - python>=3.8.1
  - numpy
  - pandas
  - scikit-learn
  - tqdm          # https://tqdm.github.io
  - ipykernel
  - matplotlib
  - pytorch::pytorch=1.5.0
  - pytorch::torchvision
  - conda-forge::opencv
  - pip
  - pip:
    - opencv-python
    - ipywidgets
    - Keras